#
# Copyright (c) Haulmont 2024. All Rights Reserved.
# Use is subject to license terms.
#

# This is a full configuration with Flowset control application + database and external Operaton + database
# See docker-compose-core.yml for a lightweight configuration that does not include Operaton.

services:
  flowset-control-app: # Flowset Сontrol web application exposed on configured port (by default 8081)
    image: flowset/flowset-control-community:latest
    container_name: flowset-control-app
    build: ..
    restart: "no"
    environment:
      MAIN_DATASOURCE_URL: "jdbc:postgresql://flowset-control-database/${FLOWSET_CONTROL_DB_NAME}"
      MAIN_DATASOURCE_USERNAME: "${FLOWSET_CONTROL_DB_USERNAME}"
      MAIN_DATASOURCE_PASSWORD: "${FLOWSET_CONTROL_DB_PASSWORD}"
      SERVER_PORT: "${FLOWSET_CONTROL_SERVER_PORT}"
      UI_LOGIN_DEFAULTUSERNAME: "${FLOWSET_CONTROL_UI_DEFAULT_USERNAME}"
      UI_LOGIN_DEFAULTPASSWORD: "${FLOWSET_CONTROL_UI_DEFAULT_PASSWORD}"
    ports:
      - "${FLOWSET_CONTROL_SERVER_PORT}:${FLOWSET_CONTROL_SERVER_PORT}"
    depends_on:
      flowset-control-database:
        condition: service_started
    healthcheck:
      test: curl --fail --silent http://localhost:$$SERVER_PORT/actuator/health | grep UP || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - flowset-control-platform-net

  flowset-control-database: # PostgresQL database used by Flowset Сontrol web application
    image: postgres:16.3
    container_name: flowset-control-database
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - flowset-control-database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${FLOWSET_CONTROL_DB_USERNAME}"
      POSTGRES_PASSWORD: "${FLOWSET_CONTROL_DB_PASSWORD}"
      POSTGRES_DB: "${FLOWSET_CONTROL_DB_NAME}"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - flowset-control-platform-net

  operaton-bpm-platform: # Operaton included REST API and web apps exposed on configured port (by default 8082)
    container_name: operaton-bpm-platform
    image: operaton/operaton:${OPERATON_RUN_VERSION}
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://operaton-bpm-platform-database:5432/${OPERATON_DB_NAME}"
      SPRING_DATASOURCE_USERNAME: "${OPERATON_DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${OPERATON_DB_PASSWORD}"
      SERVER_PORT: "${OPERATON_SERVER_PORT}"
      OPERATON_BPM_RUN_AUTH_ENABLED: "true"
      OPERATON_BPM_ADMIN_USER_ID: "${OPERATON_UI_ADMIN_USERNAME}"
      OPERATON_BPM_ADMIN_USER_PASSWORD: "${OPERATON_UI_ADMIN_PASSWORD}"
    ports:
      - "${OPERATON_SERVER_PORT}:${OPERATON_SERVER_PORT}"
    depends_on:
      operaton-bpm-platform-database:
        condition: service_started
#    command: ./operaton.sh --rest --webapps
    healthcheck:
      test: curl --fail --silent http://localhost:$$SERVER_PORT/engine-rest/engine | grep default  || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - flowset-control-platform-net

  operaton-bpm-platform-database: # PostgresQL database used by Operaton
      image: postgres:16.3
      container_name: operaton-bpm-platform-database
      ports:
        - "5433:5432"
      environment:
        - POSTGRES_USER=${OPERATON_DB_USERNAME}
        - POSTGRES_PASSWORD=${OPERATON_DB_PASSWORD}
        - POSTGRES_DB=${OPERATON_DB_NAME}
      volumes:
        - operaton-bpm-platform-database_data:/var/lib/postgresql/data
      healthcheck:
        test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
        interval: 10s
        timeout: 5s
        start_period: 10s
        retries: 5
      networks:
        - flowset-control-platform-net

volumes:
  flowset-control-database_data:
  operaton-bpm-platform-database_data:

networks:
  flowset-control-platform-net:
    driver: bridge